### ISSUE TITLE
Retrieve Metadata from package not finishing after 3.8.7 (Update for 3.9.0)

### ISSUE THREAD

**Issue by Radon7** [daishi4u/ForceCode#95]
**Describe the bug**
Even after having updated to 3.8.7 retrieving metadata from org tasks keeps to appear in running tasks even if it has ended. 
**To Reproduce**
1. Go to 'ForceCode Menu > Retrieve Package/Metadata >Retrieve by package.xml'
2. Even when alla the changes are retrieved the task keeps running

**Expected behavior**
The task should be removed from the running one

**Desktop (please complete the following information):**
 - OS: Mac OSX High Sierra 10.13
 - Version 3.8.7

**Additional context**
I don't know if it is relevant but it seems that the package.xml I'm using cannot retrieve a couple of metadata because of a bad name

**Comment by daishi4u** [comment]
You say a bad name? Would it be, for example, a class that doesn't exist or anything else that doesn't exist in the org? That would be the part that's hanging it up

**Comment by daishi4u** [comment]
Figured this out. If you don't have the meta file for the class, page, component, lightning component, and whatever else retrieves with a meta.xml file in your directory then the deploy will never finish. I'm putting a fix in for this, so basically it will finish the task but deployment will fail.

**Comment by daishi4u** [comment]
This is now fixed in v3.9.0. As I stated above, if you don't have meta.xml files (Some types don't need a meta.xml file) and you try and deploy then you will now receive a deploy error shown. There's not really a way to specifically check which one is missing right now, but maybe in the future I'll come up with something.

**Comment by Radon7** [comment]
It's me again. The problem still persists with 3.9.0. I tried from a new project but with a package with no error or missing meta-xml. When I try to retrive the metadata from package the process still hangs after it has for sure finished (I can see diff from git). 

Is there any way to debug the process so I can give more details?

**Comment by daishi4u** [comment]
Whoops, this whole time I thought you were talking about deploying because I just had a similar issue with deploy. Sorry about that. For retrieves the meta files won't matter. You can actually reproduce the issue again and toggle the vscode developer tools by going to the help menu I believe and then you'll be able to see the error it's spitting out. Once you get that, copy and paste it here.

**Comment by Radon7** [comment]
No error or whatsoever in developer console. Everything is working fine there. It just keeps hanging. I've even try to delete the extension, the force.json file and retry from scratch.

**Comment by daishi4u** [comment]
I'm not talking about the salesforce developer console, I'm talking about in vscode... it should provide some kind of information in the console output when you open the developer tools in there

**Comment by Radon7** [comment]
Yeah. I mispelled it. I mean the developer tools in VS Code. No error. Just some console logs but they are always relate to other extensions

**Comment by Radon7** [comment]
Could it be some kind of conflict with official Salesforce VS Code extension?

**Comment by daishi4u** [comment]
Oh alright, no it shouldn't be conflicting with any of the salesforce extensions. Could you possibly copy and paste your XML so I can take a look at it?

**Comment by Radon7** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>MaintenanceRequestHelper</members>
		<members>MaintenanceRequestHelperTest</members>
		<members>TestUtils</members>
		<members>T</members>
		<members>U</members>
		<members>TTest</members>
		<members>UTest</members>
		<members>WarehouseCalloutService</members>
		<members>WarehouseCalloutServiceMock</members>
		<members>WarehouseCalloutServiceTest</members>
		<members>WarehouseSyncSchedule</members>
		<members>WarehouseSyncScheduleTest</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>Case</members>
		<members>Product2</members>
		<members>Vehicle__c</members>
		<members>Work_Part__c</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>MaintenanceRequest</members>
		<name>ApexTrigger</name>
	</types>
	<version>43.0</version>
</Package>
```

**Comment by watro** [comment]
Hey, I actually have the same issue on 3.9.0 (same OS, latest vs code), upgraded directly from a pre 3.8.x version.  

It seems to happen when retrieving all metadata and at the start when the diffs when the extension initially loads.  

I actually started a clean project; I did not port the old ones.  Seems to be the only thing different from the upgrade instructions.

**Comment by daishi4u** [comment]
I wonder if there isn't an issue in the newer vsix compiler that is conflicting with mac because I changed to a newer version between releases and I don't experience this issue on windows or Linux. I can try switching back in a separate branch and then I will compile 3.9.0 again with the older version and let you guys know when it's ready. Won't be able to till later today though FYI.

**Comment by daishi4u** [comment]
@watro @Radon7 What were the last working versions that each of you used?

**Comment by Radon7** [comment]
3.8.4 for sure.I don't remember 3.8.5

**Comment by watro** [comment]
It was 3.7.1, then jumped straight to 3.9.0.

**Comment by daishi4u** [comment]
Try this version and let me know: https://github.com/daishi4u/ForceCode/raw/Testing-vsce/forcecode-3.9.1.vsix

**Comment by daishi4u** [comment]
Got it figured out. This is fixed in 3.9.1

**Comment by watro** [comment]
Thanks!  I will test it right now.

**Comment by watro** [comment]
@daishi4u It seems the bug is still there.  I can see all the updated files, but it's still showing as retrieving package 30 mins later.  

I do not see anything in the logs.  I'm going to do a bit more testing later to see if I can find anything that can help.

**Comment by daishi4u** [comment]
@watro, I'm assuming you have overwritePackageXML set to false in your settings? This is what was originally causing the bug, as I wasn't resuming the stream when downloading the files since it would skip over the package xml. Anyways, since it is still occurring for you, I'm not sure where else to look so the more details you have to offer the better. Does it do it when you open files? Refresh files? Refresh, open, and retrieve by package all use the same code so technically it should be doing it in all 3 cases for you.

**Comment by watro** [comment]
Hi @daishi4u, sorry I've been at dreamforce and have not checked email much.

v3.9.2 works perfect!
